FROM public.ecr.aws/lambda/python:3.11

# Install dependencies
COPY lambda_requirements/requirements_sentiment.txt /tmp/
RUN pip install -r /tmp/requirements_sentiment.txt -t /opt/python/

# Create the layer structure
CMD ["echo", "Layer dependencies installed"]
